#page title
page_title                                : Unread app                                # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 1517437834                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    : https://davidehlen.dev/unread-press-kit.zip                                          # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : /assets/appicon.png                        # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : Unread                                    # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Read-it-later app for iOS and iPadOS.

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : David Ehlen                                
your_link                                 : https://davidehlen.dev                     
your_city                                 : Karlsruhe                                
email_address                             : dehlen@me.com
facebook_username                         :                                           
instagram_username                        : 
twitter_username                          : da_eh
github_username                           : dehlen
youtube_username                          :



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Save articles
    description                           : Save articles from all around the web. There is no step 2.
    fontawesome_icon_name                 : bookmark
    
  - title                                 : Tags
    description                           : Organize all your saved articles with tags to always find what you are looking for.
    fontawesome_icon_name                 : tags

  - title                                 : Beautiful reading experience
    description                           : All your articles will be saved for an offline, ad-free reading experience.
    fontawesome_icon_name                 : eye

  - title                                 : Import & Export
    description                           : Sync all your articles from Instapaper or Pocket.
    fontawesome_icon_name                 : sync

  - title                                 : Dark Mode
    description                           : Of course the app comes with dark mode support baked in
    fontawesome_icon_name                 : adjust
  
  - title                                 : And more...
    description                           : Just try for yourself. The app is free as in "free". No account required.
    fontawesome_icon_name                 : dollar-sign

  - title                                 : # New Feature Title
    description                           : # New Feature Description
    fontawesome_icon_name                 : # Enter Font Awesome icon name (e.g. star). Find icons on fontawesome.com/icons.



# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.8

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
